# k8s/backendconfig.yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: stock-analyze-backendcfg
spec:
  healthCheck:
    type: HTTP
    requestPath: /
    port: 8000
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 3
