apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stock-analyze-ingress
  annotations:
    # Force resync to trigger Load Balancer update
    force-resync: "20251107-1"
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "stock-analyze-gke-cert"
spec:
  tls:
    - hosts:
        - api.stockit.live
  rules:
    - host: api.stockit.live
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stock-analyze-svc
                port:
                  number: 8000
