# service.yaml 파일로 저장하세요.
apiVersion: v1
kind: Service
metadata:
  name: stock-analyze-service # 서비스의 이름
spec:
  type: LoadBalancer # 외부에서 접근 가능한 IP를 할당받음
  selector:
    app: stock-analyze-server # 'app: stock-analyze-server' 라벨이 붙은 Pod들을 찾음
  ports:
    - protocol: TCP
      port: 80       # 외부에서 80번 포트로 접근
      targetPort: 8000 # Pod 내부의 8000번 포트로 연결